# Generated by Django 5.2.4 on 2025-08-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi Sistema', max_length=100)),
                ('description', models.TextField(default='Plataforma innovadora para la gestión integral de proyectos.')),
                ('icon', models.CharField(default='fas fa-bolt', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('company', models.CharField(default='Mi Sistema', max_length=100)),
                ('year', models.PositiveIntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
