# Generated by Django 5.2.4 on 2025-10-28 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_analyses', models.PositiveIntegerField(default=0, verbose_name='Total de Análisis')),
                ('total_faces_detected', models.PositiveIntegerField(default=0, verbose_name='Total de Rostros Detectados')),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('happiness_count', models.PositiveIntegerField(default=0)),
                ('surprise_count', models.PositiveIntegerField(default=0)),
                ('sadness_count', models.PositiveIntegerField(default=0)),
                ('anger_count', models.PositiveIntegerField(default=0)),
                ('disgust_count', models.PositiveIntegerField(default=0)),
                ('fear_count', models.PositiveIntegerField(default=0)),
                ('contempt_count', models.PositiveIntegerField(default=0)),
                ('most_frequent_emotion', models.CharField(blank=True, max_length=20, verbose_name='Emoción Más Frecuente')),
                ('average_confidence', models.FloatField(default=0.0, verbose_name='Confianza Promedio')),
                ('average_faces_per_analysis', models.FloatField(default=0.0, verbose_name='Rostros Promedio por Análisis')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadística de Emociones',
                'verbose_name_plural': 'Estadísticas de Emociones',
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='emotion_analysis/%Y/%m/%d/', verbose_name='Imagen Analizada')),
                ('faces_detected', models.PositiveIntegerField(default=0, verbose_name='Rostros Detectados')),
                ('analysis_results', models.JSONField(default=dict, help_text='Resultados completos del análisis en formato JSON', verbose_name='Resultados del Análisis')),
                ('dominant_emotion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emoción Dominante')),
                ('average_confidence', models.FloatField(default=0.0, verbose_name='Confianza Promedio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='Tiempo de Procesamiento (segundos)')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el análisis', verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Análisis de Emoción',
                'verbose_name_plural': 'Análisis de Emociones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='emotions_em_user_id_9d77a2_idx'), models.Index(fields=['dominant_emotion'], name='emotions_em_dominan_477a28_idx'), models.Index(fields=['created_at'], name='emotions_em_created_06ff78_idx')],
            },
        ),
    ]
